const FNV1A_64_OFFSET = 0xcbf29ce484222325n
const FNV1A_64_PRIME = 0x100000001b3n
const WORD_COUNT = 64n

/** Frozen word lists keep generated fallbacks stable for a given opaque id. */
const ADJECTIVES = [
  'Amber',
  'Arctic',
  'Ash',
  'Azure',
  'Blue',
  'Bold',
  'Bright',
  'Bronze',
  'Calm',
  'Cedar',
  'Clear',
  'Copper',
  'Coral',
  'Crisp',
  'Dawn',
  'Deep',
  'Ember',
  'Fern',
  'Frost',
  'Gentle',
  'Golden',
  'Green',
  'Harbor',
  'Hazel',
  'Indigo',
  'Ivory',
  'Jade',
  'Keen',
  'Lively',
  'Lunar',
  'Maple',
  'Meadow',
  'Mellow',
  'Misty',
  'Noble',
  'Ocean',
  'Olive',
  'Onyx',
  'Quiet',
  'Rapid',
  'Red',
  'River',
  'Royal',
  'Sage',
  'Silver',
  'Solar',
  'Steady',
  'Stone',
  'Sunny',
  'Swift',
  'Teal',
  'Timber',
  'True',
  'Velvet',
  'Verdant',
  'Violet',
  'Warm',
  'Wild',
  'Winter',
  'Wise',
  'Witty',
  'Yellow',
  'Young',
  'Zealous',
] as const

const NOUNS = [
  'Alpaca',
  'Antelope',
  'Badger',
  'Bear',
  'Beaver',
  'Bison',
  'Bobcat',
  'Caribou',
  'Cougar',
  'Coyote',
  'Crane',
  'Deer',
  'Dolphin',
  'Dragonfly',
  'Eagle',
  'Elk',
  'Falcon',
  'Finch',
  'Firefly',
  'Fox',
  'Gazelle',
  'Gecko',
  'Hare',
  'Heron',
  'Ibex',
  'Jay',
  'Kestrel',
  'Kingfisher',
  'Koala',
  'Lark',
  'Leopard',
  'Lynx',
  'Magpie',
  'Mantis',
  'Marten',
  'Moose',
  'Osprey',
  'Otter',
  'Owl',
  'Panda',
  'Panther',
  'Pelican',
  'Penguin',
  'Puma',
  'Quail',
  'Rabbit',
  'Raven',
  'Robin',
  'Sable',
  'Salmon',
  'Seal',
  'Shark',
  'Sparrow',
  'Stag',
  'Swan',
  'Tiger',
  'Tortoise',
  'Trout',
  'Turtle',
  'Viper',
  'Whale',
  'Wolf',
  'Wren',
  'Yak',
] as const

function fnv1a64(value: string): bigint {
  let hash = FNV1A_64_OFFSET
  for (const byte of new TextEncoder().encode(value)) {
    hash ^= BigInt(byte)
    hash = BigInt.asUintN(64, hash * FNV1A_64_PRIME)
  }
  return hash
}

/** Deterministic fallback for a session whose work has no semantic title. */
export function generatedSessionLabel(sessionId: string): string {
  const hash = fnv1a64(sessionId)
  const adjective = ADJECTIVES[Number(hash % WORD_COUNT)]
  const noun = NOUNS[Number((hash >> 6n) % WORD_COUNT)]
  return `${adjective} ${noun}`
}
