import path from 'node:path'
import { hookHostPlatform, type HookHostPlatform } from './hook-adapter.js'
import { configHome } from './install-hooks.js'
import { MISSING_LIFECYCLE_GUIDANCE_CONTEXT } from './session-activation.js'

/**
 * The OpenCode adapter.
 *
 * OpenCode's extension point is a TypeScript/JavaScript plugin module, not a
 * command hook, so it needs a different adapter rather than a different path
 * through the existing one. What it is *not* is different logic: the generated
 * plugin shells out to the same `notifai hook <event>` commands Claude Code and
 * Codex invoke, and every decision — presence, the grace window, the reply
 * wait, retirement — stays in one place.
 *
 * The three lifecycle joints map onto the same three events. OpenCode exposes
 * `chat.message` as a direct hook, while session lifecycle notifications arrive
 * through its generic `event` hook:
 *
 *   chat.message   -> user-prompt-submit   (the user is at the keyboard)
 *   session.idle   -> stop                 (the turn ended; escalate)
 *   session.deleted -> session-end         (retire local session state)
 *
 * Permission prompts deliberately stay in OpenCode. The CLI question flow
 * only escalates questions explicitly registered with `notifai ask`.
 */

/** Marker line; also how an install from another checkout is recognised. */
export const OPENCODE_PLUGIN_MARKER = '// notifai managed opencode plugin'

/** Filename we own inside whichever plugins directory is being written. */
export const OPENCODE_PLUGIN_FILENAME = 'notifai.js'

/** Bump when an installed generated file must be rewritten to remain functional. */
const OPENCODE_ADAPTER_VERSION = 11

export function opencodePluginDir(
  global: boolean,
  cwd: string,
  env: NodeJS.ProcessEnv = process.env,
  platform: NodeJS.Platform | HookHostPlatform = process.platform,
): string {
  return global
    ? path.join(configHome(env, 'OPENCODE_CONFIG_DIR', '.config/opencode', platform), 'plugins')
    : path.join(cwd, '.opencode', 'plugins')
}

export function opencodePluginPath(
  global: boolean,
  cwd: string,
  env: NodeJS.ProcessEnv = process.env,
  platform: NodeJS.Platform | HookHostPlatform = process.platform,
): string {
  return path.join(opencodePluginDir(global, cwd, env, platform), OPENCODE_PLUGIN_FILENAME)
}

export interface OpencodePluginOptions {
  /** The same stable user-level adapter every command-hook harness invokes. */
  adapterPath: string
  /** Child-process lifetime; covers grace, reply wait, and teardown headroom. */
  timeoutSeconds: number
  platform?: NodeJS.Platform | HookHostPlatform
  /** Registered Node used to interpret the Windows adapter. Ignored on POSIX. */
  nodePath?: string
}

/**
 * The generated module.
 *
 * Written as a string rather than compiled from a source file because OpenCode
 * loads a plugin module rather than a command definition. It embeds only the
 * stable user-level adapter path; mutable runtime and CLI targets live behind
 * that adapter exactly as they do for every other harness.
 *
 * Everything it does is build the hook envelope OpenCode's event gives it and
 * hand that to the CLI on stdin. It deliberately fails open: an adapter error
 * never changes OpenCode's own behavior.
 */
/**
 * The plugin body, which is the same on every platform except for how it
 * reaches the adapter.
 *
 * It was two near-identical copies — about a hundred and twenty lines each,
 * differing only in the spawn call — so every fix to the plugin had to be made
 * twice or silently apply to one platform.
 */
export function opencodePluginSource(options: OpencodePluginOptions): string {
  const { adapterPath, timeoutSeconds } = options
  // Windows cannot execute the adapter script directly, so it goes through the
  // registered Node executable and the console window is suppressed.
  const win32 = hookHostPlatform(options.platform) === 'win32'
  const nodeConstant = win32
    ? `const NODE = ${JSON.stringify(options.nodePath ?? process.execPath)}\n`
    : ''
  const spawnArguments = win32
    ? 'NODE, [ADAPTER, "hook", event, "--owner", "notifai", "--harness", "opencode"]'
    : 'ADAPTER, ["hook", event, "--owner", "notifai", "--harness", "opencode"]'
  const windowsHide = win32 ? '\n        windowsHide: true,' : ''
  return `${OPENCODE_PLUGIN_MARKER}
// Generated by \`notifai hooks install --harness opencode\`. Edits are lost on
// the next install; change the CLI instead, which is where the logic lives.
import { spawn } from "node:child_process"

${nodeConstant}const ADAPTER = ${JSON.stringify(adapterPath)}
const TIMEOUT_MS = ${timeoutSeconds * 1000}
const ADAPTER_VERSION = ${OPENCODE_ADAPTER_VERSION}
const MISSING_LIFECYCLE_GUIDANCE_CONTEXT = ${JSON.stringify(MISSING_LIFECYCLE_GUIDANCE_CONTEXT)}
const PENDING_SESSION_TITLE =
  /^New session(?: *- *[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:[.][0-9]+)?Z)?$/i

/**
 * Runs \`notifai hook <event>\`, feeding it the same JSON envelope the other
 * harnesses send. Resolves to stdout, or null if anything at all went wrong.
 */
function runHook(event, envelope) {
  return new Promise((resolve) => {
    let child
    try {
      child = spawn(${spawnArguments}, {
        env: process.env,
        shell: false,${windowsHide}
        stdio: ["pipe", "pipe", "pipe"],
      })
    } catch {
      resolve(null)
      return
    }

    let stdout = ""
    let settled = false
    const finish = (value) => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      resolve(value)
    }
    const timer = setTimeout(() => {
      child.kill("SIGTERM")
      finish(null)
    }, TIMEOUT_MS)

    child.stdout?.setEncoding("utf-8")
    child.stdout?.on("data", (chunk) => {
      stdout += chunk
    })
    // Hook stderr is diagnostics, not plugin output; discard it here.
    child.stderr?.resume()
    child.on("error", () => finish(null))
    child.on("close", () => finish(stdout))

    try {
      child.stdin?.end(JSON.stringify(envelope))
    } catch {
      finish(null)
    }
  })
}

export const NotifAIPlugin = async ({ directory, client }) => {
  const cwd = typeof directory === "string" && directory.length > 0 ? directory : process.cwd()
  const activated = new Set()

  return {
    /** Model-visible activation, independent of CLI setup and delivery state. */
    "experimental.chat.system.transform": async (input, output) => {
      const sessionID = input?.sessionID
      if (typeof sessionID !== "string" || sessionID.length === 0) return
      if (activated.has(sessionID)) return
      const resolved = await runHook("session-start", {
        session_id: sessionID,
        cwd,
        hook_event_name: "SessionStart",
      })
      const context = typeof resolved === "string" && resolved.trim().length > 0
        ? resolved.trim()
        : MISSING_LIFECYCLE_GUIDANCE_CONTEXT
      if (output.system.length === 0) {
        output.system.push(context)
      } else {
        output.system[0] = output.system[0] + "\\n\\n" + context
      }
      activated.add(sessionID)
    },

    /** Exact active-harness identity and first-party title for agent shell commands. */
    "shell.env": async (input, output) => {
      output.env.NOTIFAI_ACTIVE_HARNESS = "opencode"
      const sessionID = input?.sessionID
      if (typeof sessionID === "string" && sessionID.length > 0) {
        output.env.NOTIFAI_ACTIVE_SESSION_ID = sessionID
        try {
          const response = await client.session.get({ path: { id: sessionID } })
          const title = response?.data?.title
          if (typeof title === "string" && title.trim().length > 0) {
            if (PENDING_SESSION_TITLE.test(title.trim())) {
              output.env.NOTIFAI_ACTIVE_SESSION_LABEL_PENDING = "1"
            } else {
              output.env.NOTIFAI_ACTIVE_SESSION_LABEL = title
            }
          }
        } catch {
          // Identity remains useful when this OpenCode build cannot expose a title.
        }
      }
    },

    /**
     * Presence. The user typing is the signal every harness shares, and it is
     * also what publishes the project -> session pointer \`notifai ask\` reads.
     */
    /** Publishes the session pointer; the CLI returns no content to inject. */
    "chat.message": async (input) => {
      await runHook("user-prompt-submit", {
        session_id: input?.sessionID ?? input?.info?.sessionID,
        cwd,
        hook_event_name: "UserPromptSubmit",
      })
    },

    /** Session lifecycle events are delivered through OpenCode's event bus. */
    event: async ({ event }) => {
      if (event?.type === "session.idle") {
        await runHook("stop", {
          session_id: event?.properties?.sessionID,
          cwd,
          hook_event_name: "Stop",
        })
      } else if (event?.type === "session.deleted") {
        await runHook("session-end", {
          session_id: event?.properties?.info?.id,
          cwd,
          hook_event_name: "SessionEnd",
        })
      }
    },
  }
}
`
}

/** True when a plugin file on disk is one of ours, whoever installed it. */
export function isOurOpencodePlugin(contents: string): boolean {
  return contents.includes(OPENCODE_PLUGIN_MARKER)
}

/**
 * The interpreter and script a generated plugin will actually run.
 *
 * A plugin is a module rather than a command line, so which *build* it invokes
 * is not visible in the way it is for a settings-file handler — it is baked
 * into the two constants at the top. `doctor` needs it to answer the question
 * it exists to answer ("are two checkouts both installed?"), and without it
 * the plugin's own path stands in for the build and every OpenCode install
 * looks like a second one.
 *
 * Returns null for a plugin we did not generate, or one whose constants have
 * been edited out of recognisable shape.
 */
export function opencodePluginTarget(
  contents: string,
): { adapter: string; current: boolean; timeoutSeconds?: number; nodePath?: string } | null {
  if (!isOurOpencodePlugin(contents)) return null
  const adapter = /^const ADAPTER = (".*")$/m.exec(contents)?.[1]
  const legacyScript = /^const SCRIPT = (".*")$/m.exec(contents)?.[1]
  const node = /^const NODE = (".*")$/m.exec(contents)?.[1]
  const version = Number(/^const ADAPTER_VERSION = (\d+)$/m.exec(contents)?.[1] ?? 1)
  const timeoutMs = Number(/^const TIMEOUT_MS = (\d+)$/m.exec(contents)?.[1] ?? Number.NaN)
  if (adapter === undefined && legacyScript === undefined) return null
  try {
    return {
      adapter: JSON.parse(adapter ?? legacyScript!) as string,
      current: version === OPENCODE_ADAPTER_VERSION,
      ...(Number.isFinite(timeoutMs) ? { timeoutSeconds: timeoutMs / 1000 } : {}),
      ...(node === undefined ? {} : { nodePath: JSON.parse(node) as string }),
    }
  } catch {
    return null
  }
}
