import path from 'node:path'
import {
  applyEdits,
  createScanner,
  findNodeAtLocation,
  modify,
  parse,
  parseTree,
  printParseErrorCode,
  type JSONPath,
  type ParseError,
} from 'jsonc-parser'
import { hookHostPlatform, type HookHostPlatform } from './hook-adapter.js'
import { harnessAccountHome } from './install-hooks.js'
import {
  MISSING_LIFECYCLE_GUIDANCE_CONTEXT,
  WORKER_ACTIVATION_CONTEXT,
} from './session-activation.js'

/**
 * The OpenClaw adapter.
 *
 * OpenClaw's extension point is an in-process Gateway plugin, not a command
 * hook. The generated module shells out to the same `notifai hook <event>`
 * commands every other harness invokes, so presence, activation, and
 * retirement stay in the CLI.
 *
 *   before_prompt_build -> session-start / subagent-start  (current owner/worker guidance)
 *   message_received    -> user-prompt-submit              (User is present)
 *   agent_end           -> stop                            (the turn ended)
 *   session_end         -> session-end                     (retire local state)
 *   resolve_exec_env    -> NOTIFAI_ACTIVE_* markers        (exact Source Context)
 *
 * `command:stop` is a User abort and is deliberately not wired. Asynchronous
 * ask is unsupported until a live continuation probe.
 */

export const OPENCLAW_PLUGIN_MARKER = '// notifai managed openclaw plugin'
export const OPENCLAW_PLUGIN_ID = 'notifai'
export const OPENCLAW_PLUGIN_FILENAME = 'index.js'
export const OPENCLAW_PLUGIN_MANIFEST = 'openclaw.plugin.json'
export const OPENCLAW_PLUGIN_PACKAGE = 'package.json'

const OPENCLAW_ADAPTER_VERSION = 2

export function openclawStateDir(
  env: NodeJS.ProcessEnv = process.env,
  platform: NodeJS.Platform | HookHostPlatform = process.platform,
): string {
  const override = env['OPENCLAW_STATE_DIR']
  if (override !== undefined && override !== '') return override
  const homeOverride = env['OPENCLAW_HOME']
  if (homeOverride !== undefined && homeOverride !== '') {
    return path.join(homeOverride, '.openclaw')
  }
  return path.join(harnessAccountHome(env, platform), '.openclaw')
}

export function openclawConfigPath(
  env: NodeJS.ProcessEnv = process.env,
  platform: NodeJS.Platform | HookHostPlatform = process.platform,
): string {
  const override = env['OPENCLAW_CONFIG_PATH']
  if (override !== undefined && override !== '') return override
  return path.join(openclawStateDir(env, platform), 'openclaw.json')
}

export function openclawPluginDir(
  env: NodeJS.ProcessEnv = process.env,
  platform: NodeJS.Platform | HookHostPlatform = process.platform,
): string {
  return path.join(openclawStateDir(env, platform), 'extensions', OPENCLAW_PLUGIN_ID)
}

export function openclawPluginPath(
  env: NodeJS.ProcessEnv = process.env,
  platform: NodeJS.Platform | HookHostPlatform = process.platform,
): string {
  return path.join(openclawPluginDir(env, platform), OPENCLAW_PLUGIN_FILENAME)
}

/** A Project-scoped plugin directory an older build wrote; removal only. */
export function legacyOpenclawProjectPluginDir(cwd: string): string {
  return path.join(cwd, '.openclaw', 'extensions', OPENCLAW_PLUGIN_ID)
}

export function legacyOpenclawProjectPluginPath(cwd: string): string {
  return path.join(legacyOpenclawProjectPluginDir(cwd), OPENCLAW_PLUGIN_FILENAME)
}

export interface OpenclawPluginOptions {
  adapterPath: string
  timeoutSeconds: number
  platform?: NodeJS.Platform | HookHostPlatform
  nodePath?: string
}

export function openclawPluginManifest(): string {
  return `${JSON.stringify(
    {
      id: OPENCLAW_PLUGIN_ID,
      name: 'Notifai',
      description: 'Notifai lifecycle activation, Source Context, and session observation.',
      activation: { onStartup: true },
      configSchema: { type: 'object', additionalProperties: false },
    },
    null,
    2,
  )}\n`
}

export function openclawPluginPackage(): string {
  return `${JSON.stringify(
    {
      name: 'notifai-openclaw',
      version: '1.0.0',
      type: 'module',
      openclaw: { extensions: [`./${OPENCLAW_PLUGIN_FILENAME}`] },
    },
    null,
    2,
  )}\n`
}

export function openclawPluginSource(options: OpenclawPluginOptions): string {
  const { adapterPath, timeoutSeconds } = options
  const win32 = hookHostPlatform(options.platform) === 'win32'
  const nodeConstant = win32
    ? `const NODE = ${JSON.stringify(options.nodePath ?? process.execPath)}\n`
    : ''
  const spawnArguments = win32
    ? 'NODE, [ADAPTER, "hook", event, "--owner", "notifai", "--harness", "openclaw"]'
    : 'ADAPTER, ["hook", event, "--owner", "notifai", "--harness", "openclaw"]'
  const windowsHide = win32 ? '\n        windowsHide: true,' : ''
  return `${OPENCLAW_PLUGIN_MARKER}
// Generated by \`notifai hooks install --harness openclaw\`. Edits are lost on
// the next install; change the CLI instead, which is where the logic lives.
import { spawn } from "node:child_process"

${nodeConstant}const ADAPTER = ${JSON.stringify(adapterPath)}
const TIMEOUT_MS = ${timeoutSeconds * 1000}
const ADAPTER_VERSION = ${OPENCLAW_ADAPTER_VERSION}
const MISSING_LIFECYCLE_GUIDANCE_CONTEXT = ${JSON.stringify(MISSING_LIFECYCLE_GUIDANCE_CONTEXT)}
const WORKER_ACTIVATION_CONTEXT = ${JSON.stringify(WORKER_ACTIVATION_CONTEXT)}

function runHook(event, envelope) {
  return new Promise((resolve) => {
    let child
    try {
      child = spawn(${spawnArguments}, {
        env: process.env,
        shell: false,${windowsHide}
        stdio: ["pipe", "pipe", "pipe"],
      })
    } catch {
      resolve(null)
      return
    }

    let stdout = ""
    let settled = false
    const finish = (value) => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      resolve(value)
    }
    const timer = setTimeout(() => {
      child.kill("SIGTERM")
      finish(null)
    }, TIMEOUT_MS)

    child.stdout?.setEncoding("utf-8")
    child.stdout?.on("data", (chunk) => {
      stdout += chunk
    })
    child.stderr?.resume()
    child.on("error", () => finish(null))
    child.on("close", (code) => finish(code === 0 ? stdout : null))

    try {
      child.stdin?.end(JSON.stringify(envelope))
    } catch {
      finish(null)
    }
  })
}

function sessionKeyOf(event, ctx) {
  const key = ctx?.sessionKey ?? event?.sessionKey ?? event?.context?.sessionKey
  return typeof key === "string" ? key.trim() : ""
}

function workspaceDirOf(event, ctx) {
  const dir = ctx?.workspaceDir ?? event?.workspaceDir ?? event?.context?.workspaceDir
  return typeof dir === "string" && dir.length > 0 ? dir : process.cwd()
}

function isWorkerSession(sessionKey, ctx) {
  if (sessionKey === "") return true
  if (sessionKey.includes(":subagent:")) return true
  if (sessionKey.includes(":acp:")) return true
  if (ctx?.targetKind === "acp" || ctx?.dispatchKind === "acp") return true
  if (typeof ctx?.parentSessionKey === "string" && ctx.parentSessionKey.length > 0) return true
  return false
}

function isUserMessage(event, ctx) {
  const from = event?.from ?? event?.context?.from ?? ctx?.senderId
  if (typeof from !== "string" || from.trim().length === 0) return false
  const trigger = ctx?.trigger ?? event?.trigger
  if (trigger === "cron" || trigger === "heartbeat") return false
  return true
}

function register(api) {
  api.on("before_prompt_build", async (event, ctx) => {
    const sessionKey = sessionKeyOf(event, ctx)
    if (sessionKey === "") return { prependContext: WORKER_ACTIVATION_CONTEXT }
    const worker = isWorkerSession(sessionKey, ctx)
    const resolved = await runHook(worker ? "subagent-start" : "session-start", {
      session_id: sessionKey,
      cwd: workspaceDirOf(event, ctx),
      hook_event_name: worker ? "SubagentStart" : "SessionStart",
    })
    // Successful empty output means this Project is disabled. A later prompt
    // rechecks enablement and supplies context after compaction or re-enable.
    if (resolved !== null && resolved.trim().length === 0) return
    const context = typeof resolved === "string" && resolved.trim().length > 0
      ? resolved.trim()
      : worker ? WORKER_ACTIVATION_CONTEXT : MISSING_LIFECYCLE_GUIDANCE_CONTEXT
    return { prependContext: context }
  })

  api.on("message_received", async (event, ctx) => {
    if (!isUserMessage(event, ctx)) return
    const sessionKey = sessionKeyOf(event, ctx)
    if (sessionKey === "") return
    await runHook("user-prompt-submit", {
      session_id: sessionKey,
      cwd: workspaceDirOf(event, ctx),
      hook_event_name: "UserPromptSubmit",
    })
  })

  api.on("agent_end", async (event, ctx) => {
    const sessionKey = sessionKeyOf(event, ctx)
    if (sessionKey === "") return
    await runHook("stop", {
      session_id: sessionKey,
      cwd: workspaceDirOf(event, ctx),
      hook_event_name: "Stop",
    })
  })

  api.on("session_end", async (event, ctx) => {
    const sessionKey = sessionKeyOf(event, ctx)
    if (sessionKey === "") return
    await runHook("session-end", {
      session_id: sessionKey,
      cwd: workspaceDirOf(event, ctx),
      hook_event_name: "SessionEnd",
    })
  })

  api.on("resolve_exec_env", (event, ctx) => {
    const sessionKey = sessionKeyOf(event, ctx)
    if (sessionKey === "") return
    return {
      NOTIFAI_ACTIVE_HARNESS: "openclaw",
      NOTIFAI_ACTIVE_SESSION_ID: sessionKey,
    }
  })
}

export default {
  id: ${JSON.stringify(OPENCLAW_PLUGIN_ID)},
  name: "Notifai",
  register,
}
`
}

export function isOurOpenclawPlugin(contents: string): boolean {
  return contents.includes(OPENCLAW_PLUGIN_MARKER)
}

export function openclawPluginTarget(
  contents: string,
): { adapter: string; current: boolean; timeoutSeconds?: number; nodePath?: string } | null {
  if (!isOurOpenclawPlugin(contents)) return null
  const adapter = /^const ADAPTER = (".*")$/m.exec(contents)?.[1]
  const node = /^const NODE = (".*")$/m.exec(contents)?.[1]
  const version = Number(/^const ADAPTER_VERSION = (\d+)$/m.exec(contents)?.[1] ?? 0)
  const timeoutMs = Number(/^const TIMEOUT_MS = (\d+)$/m.exec(contents)?.[1] ?? Number.NaN)
  if (adapter === undefined) return null
  try {
    return {
      adapter: JSON.parse(adapter) as string,
      current: version === OPENCLAW_ADAPTER_VERSION,
      ...(Number.isFinite(timeoutMs) ? { timeoutSeconds: timeoutMs / 1000 } : {}),
      ...(node === undefined ? {} : { nodePath: JSON.parse(node) as string }),
    }
  } catch {
    return null
  }
}

function isJsonObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

export function parseOpenclawConfig(
  source: string,
  configFile = 'OpenClaw config',
): Record<string, unknown> {
  const errors: ParseError[] = []
  const parsed: unknown = parse(source, errors, { allowTrailingComma: true })
  if (errors.length > 0) {
    const problems = errors
      .map((error) => `${printParseErrorCode(error.error)} at offset ${error.offset}`)
      .join(', ')
    throw new Error(`${configFile} contains invalid JSONC (${problems}); refusing to write`)
  }
  if (isJsonObject(parsed)) return parsed
  throw new Error(`${configFile} is not a JSON object; refusing to write`)
}

function openclawFormattingOptions(source: string) {
  const indentation = /(?:^|\r?\n)([\t ]+)(?=")/.exec(source)?.[1] ?? '  '
  return {
    insertSpaces: !indentation.includes('\t'),
    tabSize: indentation.length,
    eol: source.includes('\r\n') ? '\r\n' : '\n',
  }
}

/** Apply one JSONC edit while leaving unrelated source ranges intact. */
export function editOpenclawConfigText(
  source: string,
  configFile: string,
  location: JSONPath,
  value: unknown,
): string {
  parseOpenclawConfig(source, configFile)
  return applyEdits(
    source,
    modify(source, location, value, { formattingOptions: openclawFormattingOptions(source) }),
  )
}

function objectAt(value: unknown): Record<string, unknown> | null {
  return isJsonObject(value) ? value : null
}

/** Install or refresh Notifai's entry with a JSONC parser edit. */
export function enableOpenclawNotifaiConfigText(source: string, configFile: string): string {
  const config = parseOpenclawConfig(source, configFile)
  const merged = mergeOpenclawNotifaiEntry(config)
  const mergedPlugins = objectAt(merged.plugins)!
  const mergedEntries = objectAt(mergedPlugins['entries'])!
  const plugins = objectAt(config.plugins)

  if (plugins === null) {
    return editOpenclawConfigText(source, configFile, ['plugins'], merged.plugins)
  }
  if (Object.hasOwn(plugins, 'entries') && !isJsonObject(plugins['entries'])) {
    return editOpenclawConfigText(source, configFile, ['plugins', 'entries'], mergedEntries)
  }
  return editOpenclawConfigText(
    source,
    configFile,
    ['plugins', 'entries', OPENCLAW_PLUGIN_ID],
    mergedEntries[OPENCLAW_PLUGIN_ID],
  )
}

interface JsoncGap {
  comma: number | null
  hasComment: boolean
}

// jsonc-parser's SyntaxKind is an ambient const enum, unavailable with
// verbatimModuleSyntax. Keep the scanner token values local to this helper.
const COMMA_TOKEN = 5
const LINE_COMMENT_TOKEN = 12
const BLOCK_COMMENT_TOKEN = 13
const EOF_TOKEN = 17

function jsoncGap(source: string, from: number, to: number): JsoncGap {
  const scanner = createScanner(source)
  scanner.setPosition(from)
  let comma: number | null = null
  let hasComment = false
  while (scanner.getPosition() < to) {
    const token = scanner.scan()
    const offset = scanner.getTokenOffset()
    if (offset >= to || token === EOF_TOKEN) break
    if (token === COMMA_TOKEN) comma = offset
    if (token === LINE_COMMENT_TOKEN || token === BLOCK_COMMENT_TOKEN) {
      hasComment = true
    }
  }
  return { comma, hasComment }
}

function removeJsoncItem(source: string, path: JSONPath): string {
  const root = parseTree(source)
  if (root === undefined) return source
  const value = findNodeAtLocation(root, path)
  if (value === undefined) return source
  const item = value.parent?.type === 'property' ? value.parent : value
  const container = item.parent
  const siblings = container?.children
  if (container === undefined || siblings === undefined) return source
  const index = siblings.indexOf(item)
  if (index < 0) return source
  const end = item.offset + item.length
  const ranges: Array<[number, number]> = []

  if (index < siblings.length - 1) {
    const gap = jsoncGap(source, end, siblings[index + 1]!.offset)
    if (gap.comma === null) return source
    if (gap.hasComment) {
      ranges.push([item.offset, end], [gap.comma, gap.comma + 1])
    } else {
      ranges.push([item.offset, gap.comma + 1])
    }
  } else {
    const trailing = jsoncGap(source, end, container.offset + container.length - 1)
    if (trailing.comma !== null) ranges.push([trailing.comma, trailing.comma + 1])
    if (index > 0) {
      const previous = siblings[index - 1]!
      const gap = jsoncGap(source, previous.offset + previous.length, item.offset)
      if (gap.comma === null) return source
      if (gap.hasComment) {
        ranges.push([gap.comma, gap.comma + 1], [item.offset, end])
      } else {
        ranges.push([gap.comma, end])
      }
    } else {
      // An inserted sole property occupies a line of its own. Recover the
      // original commented-empty object by removing that added line.
      const lineStart = source.lastIndexOf('\n', item.offset - 1) + 1
      const lineEndOffset = source.indexOf('\n', end)
      const lineEnd = lineEndOffset < 0 ? source.length : lineEndOffset
      const onOwnLine = source.slice(lineStart, item.offset).trim() === '' &&
        source.slice(end, lineEnd).trim() === (trailing.comma === null ? '' : ',')
      const lineBreakStart = source[lineStart - 2] === '\r' ? lineStart - 2 : lineStart - 1
      ranges.push([onOwnLine && lineStart > 0 ? lineBreakStart : item.offset, end])
    }
  }

  let text = source
  for (const [start, stop] of ranges.sort((a, b) => b[0] - a[0])) {
    text = text.slice(0, start) + text.slice(stop)
  }
  return text
}

function removeOpenclawLoadPathText(source: string, pluginDir: string): string {
  let text = source
  for (;;) {
    const config = parseOpenclawConfig(text)
    const paths = objectAt(objectAt(config.plugins)?.['load'])?.['paths']
    if (!Array.isArray(paths)) return text
    const index = paths.findIndex((value) => value === pluginDir)
    if (index < 0) return text
    const next = removeJsoncItem(text, ['plugins', 'load', 'paths', index])
    if (next === text) throw new Error('Could not remove the OpenClaw load path')
    text = next
  }
}

/** Remove only the entry and explicit load path owned by this installation. */
export function removeOpenclawNotifaiConfigText(
  source: string,
  configFile: string,
  pluginDir: string,
): string {
  const config = parseOpenclawConfig(source, configFile)
  const entries = objectAt(objectAt(config.plugins)?.['entries'])
  const withoutEntry = entries !== null && Object.hasOwn(entries, OPENCLAW_PLUGIN_ID)
    ? removeJsoncItem(source, ['plugins', 'entries', OPENCLAW_PLUGIN_ID])
    : source
  return removeOpenclawLoadPathText(withoutEntry, pluginDir)
}

/** Remove one older Project load path while leaving the shared entry alone. */
export function removeOpenclawLoadPathConfigText(
  source: string,
  configFile: string,
  pluginDir: string,
): string {
  parseOpenclawConfig(source, configFile)
  return removeOpenclawLoadPathText(source, pluginDir)
}

export interface OpenclawPluginLoadBlocker {
  key: 'plugins.allow' | 'plugins.deny'
  action: 'add' | 'remove'
}

export function openclawPluginLoadBlockers(
  config: Record<string, unknown>,
): OpenclawPluginLoadBlocker[] {
  const plugins = objectAt(config.plugins)
  if (plugins === null) return []
  const blockers: OpenclawPluginLoadBlocker[] = []
  const allow = plugins['allow']
  if (Array.isArray(allow) && allow.length > 0 && !allow.includes(OPENCLAW_PLUGIN_ID)) {
    blockers.push({ key: 'plugins.allow', action: 'add' })
  }
  const deny = plugins['deny']
  if (Array.isArray(deny) && deny.includes(OPENCLAW_PLUGIN_ID)) {
    blockers.push({ key: 'plugins.deny', action: 'remove' })
  }
  return blockers
}

export function openclawPluginLoadRemedy(blocker: OpenclawPluginLoadBlocker): string {
  return blocker.action === 'add'
    ? `add \"${OPENCLAW_PLUGIN_ID}\" to ${blocker.key}`
    : `remove \"${OPENCLAW_PLUGIN_ID}\" from ${blocker.key}`
}

export function openclawPluginLoadWarning(blockers: OpenclawPluginLoadBlocker[]): string | null {
  if (blockers.length === 0) return null
  return `OpenClaw will not load Notifai: ${blockers.map(openclawPluginLoadRemedy).join('; ')}.`
}

export function mergeOpenclawNotifaiEntry(
  config: Record<string, unknown>,
): Record<string, unknown> {
  const plugins =
    config.plugins !== null && typeof config.plugins === 'object' && !Array.isArray(config.plugins)
      ? { ...(config.plugins as Record<string, unknown>) }
      : {}
  const entries =
    plugins.entries !== null && typeof plugins.entries === 'object' && !Array.isArray(plugins.entries)
      ? { ...(plugins.entries as Record<string, unknown>) }
      : {}
  const existing =
    entries[OPENCLAW_PLUGIN_ID] !== null &&
    typeof entries[OPENCLAW_PLUGIN_ID] === 'object' &&
    !Array.isArray(entries[OPENCLAW_PLUGIN_ID])
      ? { ...(entries[OPENCLAW_PLUGIN_ID] as Record<string, unknown>) }
      : {}
  const hooks =
    existing.hooks !== null && typeof existing.hooks === 'object' && !Array.isArray(existing.hooks)
      ? { ...(existing.hooks as Record<string, unknown>) }
      : {}
  entries[OPENCLAW_PLUGIN_ID] = {
    ...existing,
    enabled: true,
    hooks: { ...hooks, allowConversationAccess: true },
  }
  plugins.entries = entries
  return { ...config, plugins }
}

/**
 * Drop a Project-scoped plugin directory from OpenClaw's explicit load paths,
 * leaving the shared `entries` record — and therefore the Machine plugin —
 * exactly as it was.
 */
export function removeOpenclawLoadPath(
  config: Record<string, unknown>,
  pluginDir: string,
): Record<string, unknown> {
  const currentPlugins = objectAt(config.plugins)
  const currentLoad = objectAt(currentPlugins?.['load'])
  if (currentPlugins === null || currentLoad === null || !Array.isArray(currentLoad['paths'])) {
    return config
  }
  const load = { ...currentLoad }
  const originalPaths = currentLoad['paths'] as unknown[]
  const paths = originalPaths.filter((value) => value !== pluginDir)
  if (paths.length === originalPaths.length) return config
  load.paths = paths
  return { ...config, plugins: { ...currentPlugins, load } }
}

export function removeOpenclawNotifaiEntry(
  config: Record<string, unknown>,
  pluginDir: string,
): Record<string, unknown> {
  if (!isJsonObject(config.plugins)) return config
  const currentPlugins = config.plugins as Record<string, unknown>
  const currentEntries = objectAt(currentPlugins['entries'])
  const currentLoad = objectAt(currentPlugins['load'])
  const removesEntry =
    currentEntries !== null && Object.hasOwn(currentEntries, OPENCLAW_PLUGIN_ID)
  const removesLoadPath =
    currentLoad !== null &&
    Array.isArray(currentLoad['paths']) &&
    currentLoad['paths'].includes(pluginDir)
  if (!removesEntry && !removesLoadPath) return config
  const plugins = { ...currentPlugins }
  if (removesEntry) {
    const entries = { ...currentEntries }
    delete entries[OPENCLAW_PLUGIN_ID]
    plugins.entries = entries
  }
  if (removesLoadPath) {
    plugins.load = {
      ...currentLoad,
      paths: (currentLoad['paths'] as unknown[]).filter((value) => value !== pluginDir),
    }
  }
  return { ...config, plugins }
}

/** Config-directory presence is not ownership. These files mean OpenClaw is actually configured. */
export function openclawHasGlobalEvidence(
  exists: (file: string) => boolean,
  env: NodeJS.ProcessEnv = process.env,
  platform: NodeJS.Platform | HookHostPlatform = process.platform,
): boolean {
  const state = openclawStateDir(env, platform)
  return (
    exists(openclawConfigPath(env, platform)) ||
    exists(path.join(state, 'agents')) ||
    exists(path.join(state, 'workspace'))
  )
}
